# FROM node:lts-alpine3.22

# # Install nginx on Apline Linux
# RUN apk add --no-cache nginx

# WORKDIR /usr/src/app

# COPY package*.json ./
# RUN npm ci

# COPY . .

# # Build arguments for environment variables
# # ARG VITE_API_URL
# # ENV VITE_API_URL=$VITE_API_URL

# RUN npm run build

# # Ensure nginx directories exist
# RUN mkdir -p /mywebsite
# COPY nginx-entrypoint.sh /nginx-entrypoint.sh
# RUN chmod +x /usr/src/app/nginx-entrypoint.sh

# # Copy nginx config

# COPY nginx.conf /etc/nginx/http.d/nginx.conf

# # Move dist files
# RUN cp -r ./dist/* /mywebsite/

# EXPOSE 80
# # CMD ["nginx", "-g", "daemon off;"]
# ENTRYPOINT ["/usr/src/app/nginx-entrypoint.sh"]


FROM node:lts-alpine3.22 AS build
WORKDIR /usr/src/app
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

# Copy the rest of the source files into the image.

COPY . .

# Run the build script.

RUN npm run build

FROM nginx:stable-alpine-slim AS final


COPY nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh

# Copy the production dependencies from the build stage
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist /mywebsite


# Expose the port that the application listens on.
EXPOSE 80
ENTRYPOINT ["/nginx-entrypoint.sh"]

