# FROM node:lts-alpine3.22

# # Install nginx on Apline Linux
# RUN apk add --no-cache nginx

# WORKDIR /frontend-app

# COPY package*.json ./
# RUN npm ci

# COPY . .

# # Build arguments for environment variables
# # ARG VITE_API_URL
# # ENV VITE_API_URL=$VITE_API_URL

# RUN npm run build

# # Ensure nginx directories exist
# RUN mkdir -p /frontend-app/mywebsite
# COPY nginx-entrypoint.sh /frontend-app/nginx-entrypoint.sh
# RUN sed -i 's/\r$//' /frontend-app/nginx-entrypoint.sh
# RUN chmod +x /frontend-app/nginx-entrypoint.sh

# # Copy nginx config

# COPY nginx.conf /etc/nginx/http.d/default.conf


# # Move dist files
# RUN cp -r ./dist/* /frontend-app/mywebsite/

# EXPOSE 80
# # CMD ["nginx", "-g", "daemon off;"]
# ENTRYPOINT ["/frontend-app/nginx-entrypoint.sh"]


FROM node:lts-alpine3.22 AS build
WORKDIR /frontend-app
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

# Copy the rest of the source files into the image.

COPY . .

# Run the build script.

RUN npm run build

FROM nginx:stable-alpine-slim AS final


COPY nginx-entrypoint.sh /frontend-app/nginx-entrypoint.sh
RUN sed -i 's/\r$//' /frontend-app/nginx-entrypoint.sh && \
chmod +x /frontend-app/nginx-entrypoint.sh

# Copy the production dependencies from the build stage
COPY --from=build /frontend-app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /frontend-app/dist /frontend-app/mywebsite
RUN addgroup -S frontend_group && adduser -S frontend_user -G frontend_group
RUN mkdir -p /frontend-app/mywebsite/env
RUN mkdir -p /run/nginx
# 1. Set root as the owner and frontend_group as the group for ALL folders.
# Because root owns them, frontend_user is permanently blocked from using chmod.
RUN chown -R root:frontend_group /frontend-app /etc/nginx /run/nginx /var/cache/nginx /var/log/nginx
# 2. Update the PID path in the nginx config
RUN sed -i 's|.*nginx.pid;|pid /run/nginx/nginx.pid;|g' /etc/nginx/nginx.conf
# 3. Lock down the app and config folders to Read/Execute (550).
# Owner (root): Read/Execute (5)
# Group (frontend_group): Read/Execute (5)
# Others: No Access (0)
RUN chmod -R 750 /frontend-app /etc/nginx
# 4. Grant Write access to the specific runtime folders Nginx needs to function (770).
# Owner (root): Read/Write/Execute (7)
# Group (frontend_group): Read/Write/Execute (7)
# Others: No Access (0)
RUN chmod -R 770 /run/nginx /var/cache/nginx /var/log/nginx /frontend-app/mywebsite/env
USER frontend_user

# Expose the port that the application listens on.
EXPOSE 8080
ENTRYPOINT ["/frontend-app/nginx-entrypoint.sh"]
