        server{
    listen 8080;          # Listen for IPv4
    listen [::]:8080;     # Listen for IPv6
    server_name localhost;

    root /frontend-app/mywebsite;
    index index.html;


    location / {
        try_files $uri /index.html;
    }
    }